#!/bin/bash

usb_mountpoint="/run/media/$(whoami)/EJSMAIN/"
wizardry="$HOME/wizardry/scripts-magic-spells/"
dotfiles="$HOME/dotfiles/scripts-magic-spells"

echo "[ CHECK ] USB Mount..."

# sync system scripts
echo "[ SYNCING ] scripts magic spells..."
rsync -avt "$wizardry" "$dotfiles"
# rsync -rvtp ~/wizardry/scripts-magic-spells/ ~/dotfiles/scripts-magic-spells

# sync usb
if [ -d "$usb_mountpoint" ]; then
	echo "[ SUCCESS ] USB is mounted, now syncing..."

	echo "[ SYNCING ] Scripts / Magic Spells..."
	rsync -avt "$wizardry" "$usb_mountpoint"/scripts-magic-spells/ | pv -ptrb --size "$(du -sb "$wizardry" | awk '{print $1}')" >/dev/null

	######## check Lock-encrypt: ########
	lock_encrypt_file=$(find "$usb_mountpoint" -type f -name "Lock-encrypt.tar.gz.gpg")
	if [ -n "$lock_encrypt_file" ]; then
		echo "[ AUTHENTICATE ] Decrypting Lock-encrypt directory..."
		# gpg -d --output - "gruvboxkoi.tar.gz.gpg" | tar xzf - or gpg --decrypt "gruvboxkoi.tar.gz.gpg" | tar xz
		gpg --decrypt "$lock_encrypt_file" | pv -ptrb --size "$(du -sb "$lock_encrypt_file" | awk '{print $1}')" | tar -xzv -C "$usb_mountpoint" || {
			echo "[ ERROR ] Failed to decrypt Lock-encrypt directory."
			exit 1
		}
	fi
	########################

	# can put in a function i think
	echo "[ SYNCING ] Lock-encrypt directory..."
	rsync -avt ~/Sync/Lock/ "$usb_mountpoint"/Lock-encrypt/ | pv -ptrb --size "$(du -sb ~/Sync/Lock/ | awk '{print $1}')"

	echo "[ AUTHENTICATE ] Encrypting Lock-encrypt directory..."
	tar -cvzf - "$usb_mountpoint"/Lock-encrypt | pv -ptrb --size "$(du -sb "$usb_mountpoint"/Lock-encrypt | awk '{print $1}')" | gpg --symmetric -o "$usb_mountpoint"/Lock-encrypt.tar.gz.gpg || {
		echo "[ ERROR ] Failed to encrypt Lock-encrypt directory."
		exit 1
	}

	printf "[ WARNING ] Lock-encrypt directory will be removed from USB."
	while true; do
		read -rp " Do you wish to continue? [y/N]: " yn
		case $yn in
		[Yy]*) rm -rf "$usb_mountpoint"/Lock-encrypt ;;
		[Nn]*) exit ;;
		*) printf " Error: only write 'y' or 'n'\n\n" ;;
		esac
	done

	echo "[ SUCCESS ] Synced and Encrypted!"
else
	echo "[ ERROR ] USB is not mounted. Skipping..."
fi
